{% set name = 'bob.db.iris' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
    - iris_lda.py = bob.db.iris.example.lda:main
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  script:
    - cd {{ environ.get('CI_PROJECT_DIR', environ.get('RECIPE_DIR') + '/..') }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - pip install .
    - sphinx-build -W doc $PREFIX/docs/{{ name }}
  script_env:
   - BOB_DOCUMENTATION_SERVER

requirements:
  build:
    - python
    - setuptools
    - toolchain {{ toolchain }}
    - sphinx
    - sphinx_rtd_theme
    - bob.io.base
    - bob.measure
    - bob.learn.linear
    - bob.db.base
    - matplotlib
  run:
    - python
    - setuptools
    - bob.io.base
    - bob.measure
    - bob.learn.linear
    - bob.db.base
    - matplotlib

test:
  imports:
    - {{ name }}
  commands:
    - iris_lda.py --help
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    # The doctests will run only if "CI_PROJECT_DIR" is available as an
    # environment variable. If you are testing locally, you can set it to the
    # root of your project.
    - sphinx-build -b doctest {{ environ.get('CI_PROJECT_DIR') }}/doc sphinx
  requires:
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Bob access API for Fisher's Iris Flower Dataset
  license_family: BSD
